### PR TITLE
adding lee perry head and georgia tech dragon

### PR DESCRIPTION
**Pull request by Vinc3r**
both are on CC licence
dragon: https://www.babylonjs-playground.com/#4AJ16M#24
head: https://www.babylonjs-playground.com/#4AJ16M#25

### CODE REVIEW

**Comment by Vinc3r** [comment]
'will update the available PG meshes doc page when this will merged

**Comment by deltakosh** [comment]
I think they many need a licence file with them no? (also do you mind adding glb just in case?)

**Comment by Vinc3r** [comment]
glb was already in the PR ;)
licences are now mentionned

**Comment by deltakosh** [comment]
Lol I'm getting old :)
Thanks!

**Comment by Vinc3r** [comment]
it's alright, it's sunday :)

**Pull request merged**
